debug: true

spring:
  application:
    name: demo1
  # ??????PostgreSQL?
  datasource:
    url: jdbc:postgresql://localhost:5432/userspace?currentSchema=public
    username: postgres
    password: ycy123456
  # Redis??
  data:
    redis:
      host: localhost
      port: 6379
      # ?????Redis??????????
      timeout: 10000ms
      # password: ??Redis???????????
  # JPA????????PostgreSQL???
  jpa:
    hibernate:
      ddl-auto: update  # ????/?????
    # ??PostgreSQL?????Hibernate????
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # ?????SQL???????
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # ???SQL??